[package]
name = "toggle_color_scheme"
version = "0.1.0"
authors = ["Fabien Brulport <fabien.brulport@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
yaml-rust = "0.4"
