format = """
[╭─](blue) \
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$python\
$rust\
$sudo\
$line_break\
[╰─](blue)$character"""


command_timeout = 200

[character]
success_symbol = "[➤](blue)"
error_symbol = "[➤](bold red)"
